# Generated by Django 4.2.7 on 2026-01-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Office Order', 'Office Order'), ('Notice', 'Notice'), ('Circular', 'Circular'), ('Other', 'Other')], max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('reference_id', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
