# Generated by Django 5.2.11 on 2026-02-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlog',
            name='document_type',
            field=models.CharField(choices=[('Office Order', 'Office Order'), ('Notice', 'Notice'), ('Circular', 'Circular'), ('Policy', 'Policy'), ('Other', 'Other')], max_length=50),
        ),
    ]
